name: Compile Examples

# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
  pull_request:

jobs:
  build:
    name: ${{ matrix.board.fqbn }}
    runs-on: ubuntu-latest

    env:
      SKETCHES_REPORTS_PATH: sketches-reports

    strategy:
      fail-fast: false

      matrix:
        board:
          - fqbn: Seeeduino:samd:seeed_wio_terminal
            artifact-name-suffix: seeed-wio-terminal
            serial: true
            softwareserial: true
          - fqbn: Seeeduino:samd:Seeed_femto_m0
            artifact-name-suffix: seeed-femto-m0
            serial: true
            softwareserial: true
          - fqbn: Seeeduino:samd:seeed_XIAO_m0
            artifact-name-suffix: seeed-XIAO-m0
            serial: true
            softwareserial: true
          - fqbn: Seeeduino:samd:Wio_Lite_MG126
            artifact-name-suffix: wio-lite-MG126
            serial: true
            softwareserial: true
          - fqbn: Seeeduino:samd:WioGPS
            artifact-name-suffix: wio-gps
            serial: true
            softwareserial: true
          - fqbn: Seeeduino:samd:zero
            artifact-name-suffix: Seeeduino-Zero
            serial: true
            softwareserial: true
          - fqbn: Seeeduino:samd:rolawan
            artifact-name-suffix: Seeeduino-LoRaWAN
            serial: true
            softwareserial: true
          - fqbn: Seeeduino:samd:Wio_LTE_CAT
            artifact-name-suffix: Wio-LTE-CAT
            serial: true
            softwareserial: true
          - fqbn: Seeeduino:samd:seeed_grove_ui_wireless
            artifact-name-suffix: seeed-grove-ui-wireless
            serial: true
            softwareserial: true

        # Make board type-specific customizations to the matrix jobs
        include:
          - board:
              # Boards with Serial interface
              serial: true
            # Compile these sketches in addition to the ones compiled for all boards
            serial-sketch-paths: |
              - libraries/SPI
              - libraries/Wire
          - board:
              serial: false
            serial-sketch-paths: ""
          - board:
              # Boards compatible with the SoftwareSerial library
              softwareserial: true
            softwareserial-sketch-paths: |
              - libraries/SoftwareSerial
          - board:
              softwareserial: false
            softwareserial-sketch-paths: ""

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile examples
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: ${{ matrix.board.fqbn }}
          platforms: |
            # Use Boards Manager to install the latest release of the platform to get the toolchain.
            - name: Seeeduino:samd
              source-url: https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json
          sketch-paths: |
            # Compile these sketches for all boards
            # - libraries/EnergySaving/examples/WakeUpOnExternalInterrupt
            # - libraries/EnergySaving/examples/WakeUpOnRTCInterrupt
            # Board-specific sketches
            ${{ matrix.serial-sketch-paths }}
            ${{ matrix.softwareserial-sketch-paths }}
          enable-deltas-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}

      - name: Save sketches report as workflow artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: ${{ env.SKETCHES_REPORTS_PATH }}
          name: sketches-report-${{ matrix.board.artifact-name-suffix }}
